package models

type SecretServerResponse struct {
	ID               int    `json:"id"`
	Name             string `json:"name"`
	SecretTemplateID int    `json:"secretTemplateId"`
	FolderID         int    `json:"folderId"`
	Active           bool   `json:"active"`
	Items            []struct {
		ItemID           int    `json:"itemId"`
		FileAttachmentID any    `json:"fileAttachmentId"`
		Filename         any    `json:"filename"`
		ItemValue        string `json:"itemValue"`
		FieldID          int    `json:"fieldId"`
		FieldName        string `json:"fieldName"`
		Slug             string `json:"slug"`
		FieldDescription string `json:"fieldDescription"`
		IsFile           bool   `json:"isFile"`
		IsNotes          bool   `json:"isNotes"`
		IsPassword       bool   `json:"isPassword"`
		IsList           bool   `json:"isList"`
		ListType         string `json:"listType"`
	} `json:"items"`
	LauncherConnectAsSecretID          int    `json:"launcherConnectAsSecretId"`
	CheckOutMinutesRemaining           int    `json:"checkOutMinutesRemaining"`
	CheckedOut                         bool   `json:"checkedOut"`
	CheckOutUserDisplayName            string `json:"checkOutUserDisplayName"`
	CheckOutUserID                     int    `json:"checkOutUserId"`
	IsRestricted                       bool   `json:"isRestricted"`
	IsOutOfSync                        bool   `json:"isOutOfSync"`
	OutOfSyncReason                    string `json:"outOfSyncReason"`
	AutoChangeEnabled                  bool   `json:"autoChangeEnabled"`
	AutoChangeNextPassword             string `json:"autoChangeNextPassword"`
	RequiresApprovalForAccess          bool   `json:"requiresApprovalForAccess"`
	RequiresComment                    bool   `json:"requiresComment"`
	CheckOutEnabled                    bool   `json:"checkOutEnabled"`
	CheckOutIntervalMinutes            int    `json:"checkOutIntervalMinutes"`
	CheckOutChangePasswordEnabled      bool   `json:"checkOutChangePasswordEnabled"`
	AccessRequestWorkflowMapID         int    `json:"accessRequestWorkflowMapId"`
	ProxyEnabled                       bool   `json:"proxyEnabled"`
	SessionRecordingEnabled            bool   `json:"sessionRecordingEnabled"`
	RestrictSSHCommands                bool   `json:"restrictSshCommands"`
	JumpboxRouteID                     any    `json:"jumpboxRouteId"`
	AllowOwnersUnrestrictedSSHCommands bool   `json:"allowOwnersUnrestrictedSshCommands"`
	IsDoubleLock                       bool   `json:"isDoubleLock"`
	DoubleLockID                       int    `json:"doubleLockId"`
	EnableInheritPermissions           bool   `json:"enableInheritPermissions"`
	PasswordTypeWebScriptID            int    `json:"passwordTypeWebScriptId"`
	SiteID                             int    `json:"siteId"`
	EnableInheritSecretPolicy          bool   `json:"enableInheritSecretPolicy"`
	SecretPolicyID                     int    `json:"secretPolicyId"`
	LastHeartBeatStatus                string `json:"lastHeartBeatStatus"`
	LastHeartBeatCheck                 string `json:"lastHeartBeatCheck"`
	FailedPasswordChangeAttempts       int    `json:"failedPasswordChangeAttempts"`
	LastPasswordChangeAttempt          string `json:"lastPasswordChangeAttempt"`
	SecretTemplateName                 string `json:"secretTemplateName"`
	ResponseCodes                      []any  `json:"responseCodes"`
	WebLauncherRequiresIncognitoMode   bool   `json:"webLauncherRequiresIncognitoMode"`
	Message                            string `json:"message"`
}
